services:
  app_blue:
    image: "${BLUE_IMAGE}"
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
    ports:
      - "${BLUE_HOST_PORT}:${PORT}"
    restart: unless-stopped

  app_green:
    image: "${GREEN_IMAGE}"
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
    ports:
      - "${GREEN_HOST_PORT}:${PORT}"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app_blue
      - app_green
    ports:
      - "${NGINX_HOST_PORT}:80"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - APP_PORT=${PORT}
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./nginx/start.sh:/start.sh:ro
    command: ["/bin/sh","/start.sh"]
    restart: unless-stopped
